### ISSUE TITLE
Downloading from OpenStreetMap

### ISSUE THREAD

**Issue by simon-tarr** [MilesMcBain/slippymath#14]
Forgive the really basic question but; how could I download data from Open Street Maps? The `slippymath` documentation provides a nice explanation for Mapbox but OSM is missing. I've read through the `slippymath` documentation but can't find an example for OSM. Apologies if it exists and I've missed it!

To summarise my problem, I can't figure out how the OSM URL string marries up with `pmap`:

```
library(slippymath)
library(sf)
library(purrr)
library(curl)
library(glue)

uluru_bbox <- st_bbox(c(xmin = 131.02084,
              xmax = 131.0535,
              ymin = -25.35461,
              ymax = -25.33568),
              crs = st_crs("+proj=longlat +ellps=WGS84"))

tile_grid <- bbox_to_tile_grid(uluru_bbox, max_tiles = 15)

mapbox_query_string <- paste0("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")

images <- pmap(tile_grid$tiles,
            function(x, y, zoom){
            outfile <- glue("{x}_{y}.jpg")
            curl_download(url = glue(mapbox_query_string), destfile = outfile) 
            outfile 
                },
                zoom = tile_grid$zoom)

```
```
 Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 's' not found 
```
Any help would be appreciated. Many thanks.

**Comment by MilesMcBain** [comment]
Hi @simon-tarr thanks for the question.

Here's some info on {s} I found at https://leafletjs.com/reference-1.4.0.html#tilelayer : 

> {s} means one of the available subdomains (used sequentially to help with browser parallel requests per domain limitation; subdomain values are specified in options; a, b or c by default, can be omitted), {z} — zoom level, {x} and {y} — tile coordinates. {r} can be used to add "@2x" to the URL to load retina tiles. 

So `{s}` need not be interpolated. It can be omitted or hard coded to 'a', 'b', or 'c'. See the OSM Urls in the Servers table here: https://wiki.openstreetmap.org/wiki/Tiles

The purpose of `{s}` seems to be to allow you to make many requests in paralell against multiple servers instead of smashing one - if you have demanding realtime tile fetching needs. In the case of downloading small numbers of tiles for offline use it's probably irrelevant.

For background, `pmap` is used to here iterate over the rows of `tile_grid$tiles` - a dataframe. Each column of a row becomes a named argument in the mapped function call. So if you did want to use `{s}` you would need to introduce a column called 's' into `tile_grid$tiles`, e.g. `tile_grid$tiles$s <- "a"` to always use `a.tile.openstreetmap.org` you could use some alternating scheme within `tile_grid$tiles$s` if you wanted to spread the load across the a, b, and c subdomains.

Finally I suggest you check the OSM tile usage policy: https://operations.osmfoundation.org/policies/tiles/ to make sure you're operating within the spirit of that.

**Comment by rCarto** [comment]
Hello, 
The {s} parameter is definitely a problem in this issue, and your suggestion to add a `tile_grid$tiles$s` column works fine. 
But, I found that (as most of the tiles exposed via these providers http://leaflet-extras.github.io/leaflet-providers/preview/), osm tiles are png files.  
For a reason I do not fully understand, RasterBrick directly built with `raster::brick()` cannot (?) be merged together to form a composed RasterBrick (the result is a RasterLayer...).
Reading the file with `png::readPNG()` first seems to work fine. 

The following code modifies the readme example, taking into account the tiles extensions and the subdomain urls. There is also a modified version of `compose_tile_grid()` to manage png files. 

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
library(slippymath)
library(purrr)
library(curl)
library(glue)

uluru_bbox <-
  st_bbox(
    c(
      xmin = 131.02084,
      xmax = 131.0535,
      ymin = -25.35461,
      ymax = -25.33568
    ),
    crs = st_crs("+proj=longlat +ellps=WGS84")
  )

tile_grid <- bbox_to_tile_grid(uluru_bbox, zoom = 13)


# osm query for png
query_string <- 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
# query_string <- "https://stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png"
# or stamen for jpg
# query_string <- "https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg"
# subdomains management
tile_grid$tiles$s <- sample(c("a","b","c"), nrow(tile_grid$tiles), replace = T)
# extension management 
tile_grid$ext <- substr(query_string, 
                        nchar(query_string)-2, 
                        nchar(query_string))

images <-
  pmap(tile_grid$tiles,
       function(s, x, y, z, ext){
         outfile <- glue("{x}_{y}.{ext}")
         curl_download(url = glue(query_string),
                       destfile = outfile) 
         outfile 
       },
       z = tile_grid$zoom,
       ext = tile_grid$ext
  )

# png compatible compose_tile_grid
compose_tile_grid <- function (tile_grid, images){
  bricks <- purrr::pmap(.l = list(x = tile_grid$tiles$x, 
                                  y = tile_grid$tiles$y, 
                                  image = images, 
                                  ext = tile_grid$ext), 
                        .f = function(x, y, image, zoom, ext) {
                          bbox <- tile_bbox(x, y, zoom)
                          if (ext=="png"){
                            image <- png::readPNG(image)
                          }
                          raster_img <- raster::brick(image, 
                                                      crs = attr(bbox, "crs")$proj4string)
                          raster::extent(raster_img) <- raster::extent(bbox[c("xmin", 
                                                                              "xmax",
                                                                              "ymin", 
                                                                              "ymax")])
                          raster_img
                        }, zoom = tile_grid$zoom)
  rout <- do.call(raster::merge, bricks)
  rout
}

uluru <- compose_tile_grid(tile_grid, images)
raster_to_png(uluru, "uluru.png")
```
<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![uluru](https://user-images.githubusercontent.com/3041254/68403043-996f4480-017c-11ea-8b03-a4989cb9d377.png)

Any thoughts on that @MilesMcBain ?

**Comment by mdsumner** [comment]
fwiw can do this more directly with the gdal warp applib, this is wrapped up (for example) in {whatarelief} but merely as an example using the {vapour} package

``` r
library(whatarelief)
ex <- c(xmin = 131.02084, xmax = 131.0535, ymin = -25.35461, ymax = -25.33568)
par(mar = rep(0, 4))
im <- streetmap(extent = ex, projection = "OGC:CRS84", dimension = dev.size("px"))
ximage::ximage(im, extent = ex, asp = 1/cos(mean(ex[3:4]) * pi/180))
```

![](https://i.imgur.com/T7152PK.png)

<sup>Created on 2023-01-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Because it is the warper you don't get approximately your extent based on the tiles, you get exactly that extent in whatever projection it is you specify. I'm hoping we can get the best of the tile packages consolidated better, separate providers from downloaders and GDAL-getters, hopefully one day we can be a little less scattered. I'm exploring what's about, I like the idea of updating {slippymath} to remove any dependency on raster too, I think it's a shame that it's using raster to load data but that's how this goes. 

There's also a lot of work in paleolimbot/rosm for quadkey logic, and obviously @rCarto package {maptiles}. I'm scouting around for some ways forward if anyone is interested.

**Comment by MilesMcBain** [comment]
Thanks Mike!

**Comment by MilesMcBain** [comment]
Thanks Mike!

**Comment by MilesMcBain** [comment]
Thanks Mike!
